server {
    listen       8080;
    server_name  localhost;
 
    location / {
        root /opt/data/;
        index hotels.json;
        dav_methods PUT DELETE MKCOL COPY MOVE;
        dav_access user:rw group:rw all:rw;
    }
}